#Add MyCloset
POST http://localhost:8080/items
Content-Type: application/json

{
    "itemName": "12",
    "category":1, 
    "image": "https://img.icons8.com/?size=80&id=mw8n5jxdoKlM&format=png"
}

###
GET http://localhost:8080/items

###
DELETE http://localhost:8080/items/5

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "userId" : "LALA",
  "password" : "LOCO12345",
  "name" : "yujin",
  "gender" : false
}