
POST http://localhost:8080/items
Content-Type: application/json

{
    "itemName": "12",
    "category":1, 
    "image": "https://img.icons8.com/?size=80&id=mw8n5jxdoKlM&format=png"
}

###
GET http://localhost:8080/api/items

###
DELETE http://localhost:8080/items/5

###
GET http://localhost:8080/api/categories

###
POST http://localhost:8080/api/coordis

{
  "date": "2023-02-28",
	"photo":" ",
	"temperature": 0,
	"weather": 0
}
//weather 이 0이 되면 기본값으로 인식이 돼서 에러가 발생함 
//그럼 0 이상의 숫자를 입력하도록 설정해야하납? 
###
GET http://localhost:8080/api/coordis?year=2023&month=02

###
POST http://localhost:8080/api/users

{

  "Id" : "Ofg",
  "Password" : "GOING",
  "Name" : "세일러문",
  "Birthday" : "2004-12-14",
  "PhoneNumber" : "010-4444-5555",
  "Gender" : 0
}

###
DELETE http://localhost:8080/api/coordis/3

###
POST  http://localhost:8080/api/login

{
  "Id" : "O",
  "Password" : "GOING"
}